import { sequelize, Card } from '../../sql';

describe('Sql', () => {
  describe('Card', () => {
    describe('Model', () => {
      it('should be a model', () => {
        expect(Card.name).toBe('card');
        expect(Card.tableName).toBe('cards');

        expect(Card.attributes.id.primaryKey).toBe(true);
        expect(Card.attributes.id.defaultValue).toBeDefined();

        expect(Card.attributes.index.allowNull).toBe(false);

        expect(Card.attributes.power.fieldName).toBe('power');
        expect(Card.attributes.toughness.fieldName).toBe('toughness');
        expect(Card.attributes.loyalty.fieldName).toBe('loyalty');
        expect(Card.attributes.mana.fieldName).toBe('mana');
        expect(Card.attributes.rarity.fieldName).toBe('rarity');
        expect(Card.attributes.artist.fieldName).toBe('artist');

        expect(Card.attributes.createdAt.allowNull).toBe(false);
        // eslint-disable-next-line no-underscore-dangle
        expect(Card.attributes.createdAt._autoGenerated).toBe(true);

        expect(Card.attributes.updatedAt.allowNull).toBe(false);
        // eslint-disable-next-line no-underscore-dangle
        expect(Card.attributes.updatedAt._autoGenerated).toBe(true);

        expect(Card._timestampAttributes.createdAt).toBe('createdAt'); // eslint-disable-line no-underscore-dangle
        expect(Card._timestampAttributes.updatedAt).toBe('updatedAt'); // eslint-disable-line no-underscore-dangle
      });
    });

    describe('Instance', () => {
      const index = 4;

      beforeEach(() => sequelize.sync({ force: true })
        .then(() => Card.create({ index })));

      it('should be an instance of Card', () => Card.findOne({ where: { index } })
        .then((card) => {
          expect(card.dataValues).toBeInstanceOf(Object);
          expect(card.isNewRecord).toBe(false);


          expect(card.id).toMatch(/^.+-.+-.+-.+$/);
          expect(card.index).toBe(index);
          expect(card.createdAt).toBeInstanceOf(Date);
          expect(card.updatedAt).toBeInstanceOf(Date);
        }));

      it('should retrieve 1 Card', () => Card.findAll()
        .then((cards) => {
          expect(cards).toHaveLength(1);

          const [card] = cards;
          expect(card.index).toBe(index);
        }));
    });
  });
});
